# Generated by Django 5.1 on 2025-02-08 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('skills', models.TextField(blank=True, default='', null=True)),
                ('location', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume_document_storage')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('matched_location', models.CharField(blank=True, max_length=255, null=True)),
                ('matched_position', models.CharField(blank=True, max_length=255, null=True)),
                ('matched_education', models.TextField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobposting')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumedocument')),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hired', models.DateField(blank=True, null=True)),
                ('resigned', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_entries', to='jobseeker.resumedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('finished', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_entries', to='jobseeker.resumedocument')),
            ],
        ),
    ]
