# Generated by Django 5.1 on 2025-02-08 07:56

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_established', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccreditationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('Direct Company', 'Direct Company'), ('Manpower Agencies/Cooperative', 'Manpower Agencies/Cooperative'), ('For Overseas Manpower Agency', 'For Overseas Manpower Agency')], default='Direct Company', max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('document_text', models.TextField(blank=True, null=True)),
                ('sec_registration', models.FileField(blank=True, null=True, upload_to='accreditation_documents/sec_registration/')),
                ('dti_permit', models.FileField(blank=True, null=True, upload_to='accreditation_documents/dti_permit/')),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='accreditation_documents/business_permit/')),
                ('latest_job_posting', models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_posting/')),
                ('latest_job_order_with_qualifications', models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_job_order_with_qualifications/')),
                ('latest_payment_receipt', models.FileField(blank=True, null=True, upload_to='accreditation_documents/latest_payment_receipt/')),
                ('no_pending_case_certificate', models.FileField(blank=True, null=True, upload_to='accreditation_documents/no_pending_case_certificate/')),
                ('dole_permit', models.FileField(blank=True, null=True, upload_to='accreditation_documents/dole_permit/')),
                ('bir_registration', models.FileField(blank=True, null=True, upload_to='accreditation_documents/bir_registration/')),
                ('sss_membership_registration', models.FileField(blank=True, null=True, upload_to='accreditation_documents/sss_membership_registration/')),
                ('tied_companies_list', models.FileField(blank=True, null=True, upload_to='accreditation_documents/tied_companies_list/')),
                ('phil_job_net_registration', models.FileField(blank=True, null=True, upload_to='accreditation_documents/phil_job_net_registration/')),
                ('poea_permit', models.FileField(blank=True, null=True, upload_to='accreditation_documents/poea_permit/')),
                ('company_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('no_of_vacancies', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employer.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/applicant_documents/'), upload_to='applicant_documents/')),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_jobs', models.ManyToManyField(related_name='applicants', to='employer.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='MatchedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matched_date', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_candidates', to='employer.applicant')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_candidates', to='employer.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to='employer.applicant')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to='employer.jobposting')),
            ],
        ),
    ]
